Loading numpy

In [3]:
import numpy as np

In [12]:
a = np.array([1,2,3], dtype = 'int16')
print(a)
a

[1 2 3]


array([1, 2, 3], dtype=int16)

In [6]:
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# get Dimension
b.ndim

2

In [8]:
# Get Shape
a.shape

(3,)

In [9]:
b.shape

(2, 3)

In [10]:
# Get Type
a.dtype

dtype('int32')

In [ ]:
# Get Size
a.itemsize

In [4]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
a.shape
# Get a specific element [r,c]
print(a[1,3])
print(a[1,-1])


8
8


In [17]:
# get a specific Row
a[0, :]

array([1, 2, 3, 4])

In [18]:
# get a specific column
a[:, 2]

array([3, 7])

In [19]:
# advanced [startindex, endindex, stepindex]
a[0, 1:4:2]

array([2, 4])

In [24]:
# changing the values
a[0,2] = 20
a
a[:, 1] = 3
a
a[:, 3] = [10,11]
a

array([[ 1,  3, 20, 10],
       [ 5,  3,  7, 11]])

In [26]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [28]:
c[:, 1]

array([[3, 4],
       [7, 8]])

In [30]:
c[:, 1] = [[11,22], [33,44]]
c

array([[[ 1,  2],
        [11, 22]],

       [[ 5,  6],
        [33, 44]]])

Initializing different types of Arrays


In [33]:
# All zero matrix
np.zeros((5,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [34]:
# All one matric
np.ones(5)

array([1., 1., 1., 1., 1.])

In [35]:
# any other numbers
np.full((2,2), 9)

array([[9, 9],
       [9, 9]])

In [36]:
# any number full_like
np.full_like(c,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [38]:
# Random decimal numbers
np.random.rand(4,2)
np.random.random_sample(c.shape)

array([[[0.03122732, 0.7044049 ],
        [0.19242415, 0.61297625]],

       [[0.47755334, 0.95120266],
        [0.20052447, 0.50254286]]])

In [41]:
# Random integer matrix
np.random.randint(-4,8,size = (3,3))
np.random.randint(8,size = (3,3))

array([[4, 3, 5],
       [3, 1, 3],
       [7, 5, 6]])

In [44]:
# The identity matrix
np.identity(3, dtype = "int32")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [45]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [50]:
# Repeat an Array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis = 0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [53]:
out = np.ones((5,5))
out

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
z = np.zeros((3,3))
z
z[1,1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [60]:
out[1:4, 1:4] = z
out

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Be careful when copying arrays!!!!

In [61]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
a

array([1, 2, 3])

Mathematics

In [62]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [63]:
a+2

array([3, 4, 5, 6])

In [64]:
a-2

array([-1,  0,  1,  2])

In [65]:
a**2


array([ 1,  4,  9, 16])

## Linear Algebra

In [67]:
a = np.ones((2,3))
b = np.full((3,2), 4)
print(a,b)

[[1. 1. 1.]
 [1. 1. 1.]] [[4 4]
 [4 4]
 [4 4]]


In [68]:
np.matmul(a,b)

array([[12., 12.],
       [12., 12.]])

#### Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

 Determinant
 Trace
 Singular Vector Decomposition
 Eigenvalues
 Matrix Norm
 Inverse
 Etc ...

#### Statistics

In [5]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.min(stats)

1

In [9]:
np.min(stats, axis = 1)

array([1, 4])

In [8]:
np.max(stats)

6

In [11]:
np.sum(stats)
np.sum(stats, axis = 1)

array([ 6, 15])

### Reorganizing Arrays


In [18]:
before = np.array([[1,2,3,4], [4,5,6,7]])
# before.shape
after = before.reshape((8,1))
after

array([[1],
       [2],
       [3],
       [4],
       [4],
       [5],
       [6],
       [7]])

In [19]:
after = before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]]])

### Miscelleneous